name: Build Nuget Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  core:
    name: Build and Package - Core
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: | 
            6.0.x
      - name: Build
        run: dotnet build .\Box.V2.Core
      - name: Pack
        run: dotnet pack .\Box.V2.Core
      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Box.V2.Core.${{ github.run_attempt }}
          path: .\Box.V2.Core\x64\Release\*